server:
  port: 9090
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jenkins
    username: election
    password: election

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type: INFO

app:
  allowed-origins:
    http://41.38.83.137:8060,http://localhost:4200
